steps:
  - name: "Build :docker: image and push it to registry :rocket:"
    command: .buildkite/build.sh
    branches: master

  - wait: ~
    continue_on_failure: true
  - command: rm -rf /tmp/${BUILDKITE_PIPELINE_SLUG}

  # Staging release
  - wait
  - name: "Deploy to ECS Staging cluster"
    command: .buildkite/deploy.sh -c demo-staging -s nginx-staging-service -a 457557654038 -p poc
    branches: master
  - wait
   # Green Production release
   # wait for unblock by team member
  - block: ":red_button: Trigger Green Production Release :red_button:"
    branches: master

  - name: ":rocket: Deploying to ECS Green Production"
    command:  .buildkite/deploy.sh -c demo-prod -s nginx-prod-green -a 457557654038 -p poc
    branches: master

   # Blue Production release
   # wait for unblock by team member
  - block: ":red_button: Trigger Blue Production Release :red_button:"
    branches: master

  - name: ":rocket: Switching Green to Blue Production"
    command:  .buildkite/blue-green-flip.sh
    branches: master
