steps:
  - name: "Build :docker: image and push it to registry :rocket:"
    command: .buildkite/build.sh
    branches: master

  - wait: ~
    continue_on_failure: true
  - command: rm -rf /tmp/${BUILDKITE_PIPELINE_SLUG}

  # Staging release
  - wait
  - name: "Deploy to ECS Staging cluster"
    command: /usr/local/bin/ecs-deploy -c demo-staging -n nginx-staging-service -i 457557654038.dkr.ecr.ap-southeast-1.amazonaws.com/nginx:${BUILDKITE_COMMIT::6} -p poc -v --skip-deployments-check -t 240
    branches: master
  - wait
   # Production release
   # wait for unblock by team member
  - block: ":red_button: Trigger Production Release :red_button:"
    branches: master

  - name: ":rocket: Deploying to ECS Production Green"
    command: ecs-deploy -c demo-prod -n nginx-prod-service -i 457557654038.dkr.ecr.ap-southeast-1.amazonaws.com/nginx:${BUILDKITE_COMMIT::6} -p poc -v --skip-deployments-check -t 240
    branches: master

